/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-04-10

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
#define DMA_ADC
#define TIM15_TRGO

uint16_t dataAdc[1024];
uint8_t statusWork = 0;

#define DMA_DATA_ADC_RDY	(1 << 0)

void DMA1_Channel1_IRQHandler() {
	DMA1->IFCR |= DMA_IFCR_CTCIF1;
	GPIOC->ODR ^= GPIO_ODR_8;

	statusWork |= DMA_DATA_ADC_RDY;
}

void ADC_dma_init() {
	RCC->AHBENR |= RCC_AHBENR_DMA1EN;

	DMA1_Channel1->CNDTR = 32;
	DMA1_Channel1->CMAR = (uint32_t)&dataAdc[0];
	DMA1_Channel1->CPAR = (uint32_t)(&(ADC1->DR));

	DMA1_Channel1->CCR |= DMA_CCR_MINC;
	DMA1_Channel1->CCR |= DMA_CCR_PSIZE_0;
	DMA1_Channel1->CCR |= DMA_CCR_MSIZE_0;
	DMA1_Channel1->CCR &= ~DMA_CCR_DIR;	//from p to m

	DMA1_Channel1->CCR |= DMA_CCR_CIRC;

	DMA1_Channel1->CCR |= DMA_CCR_TCIE;

	NVIC_SetPriority(DMA1_Ch1_IRQn, 5);
	NVIC_EnableIRQ(DMA1_Ch1_IRQn);
	__enable_irq();

	DMA1_Channel1->CCR |= DMA_CCR_EN;
}

void ADC_init() {
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER0;	//pa0 as analog function

	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
	GPIOB->MODER |= GPIO_MODER_MODER0;	//pb0 as analog function

	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	RCC->CR2 |= RCC_CR2_HSI14ON;


	ADC1->CFGR1 |= ADC_CFGR1_CONT;
	ADC1->CFGR1 |= ADC_CFGR1_OVRMOD;
	ADC1->SMPR &= ~ADC_SMPR1_SMPR;	//0x07 239.5 adc cycles
	ADC1->CHSELR = 0x0001;	//1 and 8 channels are ON...

#ifdef DMA_ADC
	ADC_dma_init();
	ADC1->CFGR1 |= ADC_CFGR1_DMACFG;
	ADC1->CFGR1 |= ADC_CFGR1_DMAEN;
#endif

#ifdef TIM15_TRGO
	ADC1->CFGR1 &= ~ADC_CFGR1_CONT;
	ADC1->CFGR1 |= ADC_CFGR1_DISCEN;
	ADC1->CFGR1 |= ADC_CFGR1_EXTEN_0;
	ADC1->CFGR1 |= ADC_CFGR1_EXTSEL_2;
#endif

	ADC1->CR |= ADC_CR_ADEN;
	while((ADC1->ISR & ADC_ISR_ADRDY) != ADC_ISR_ADRDY);
	ADC1->CR |= ADC_CR_ADSTART;
}

int processStatus() {
	switch (statusWork) {
		case DMA_DATA_ADC_RDY :
			statusWork &= ~DMA_DATA_ADC_RDY;
			//обрабатываем данные
		break;
	}

	return statusWork;
}

void tim15_as_trgO() {
	RCC->APB2ENR |= RCC_APB2ENR_TIM15EN;
	TIM15->ARR = 500;
	TIM15->PSC = 8;
#ifdef TIM15_TRGO
	TIM15->CR2 |= TIM_CR2_MMS_1;	//update tim15_trgO
#endif
	TIM15->CR1 |= TIM_CR1_CEN;
}

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODER8_0;
	uint16_t dataADC[2];
	uint8_t currentNumAdcCh = 0;

	ADC_init();

	tim15_as_trgO();

	while(1) {
		processStatus();

	}
}



